# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.5.1'

group :test do
  gem 'rspec'
end

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'rubocop', require: false
end

group :development, :test do
  gem 'pry'
end